### ISSUE TITLE
[Feature] Add support for text pages

### ISSUE THREAD

**Issue by GeeWizWow** [bryoz/reactphoto#7]
- Setup script should read text files located in source directory
- Should only support markdown files
- Should either:
        - Include markdown in data.json
        - Include markdown parsed to html in data.json
        - Include link to markdown file for runtime parsing
        - Include link to generated html file

All HTML should be sanitized to reduce risk of XSS vuln

https://www.npmjs.com/package/marked
https://github.com/rexxars/react-markdown

**Comment by bryoz** [comment]
I think, given our approach with metadata to build page content, we can probably waive this.

It might be useful to support .md for About page, but limited beyond that, given the nature of the application.
